"""ajuste

Revision ID: bf60629b28f5
Revises: 
Create Date: 2026-05-02 22:27:21.212935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf60629b28f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercicio',
    sa.Column('id_exercicio', sa.Integer(), nullable=False),
    sa.Column('nome_exercicio', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_exercicio', name=op.f('pk_exercicio'))
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('sobrenome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario')),
    sa.UniqueConstraint('email', name=op.f('uq_usuario_email'))
    )
    op.create_table('atleta',
    sa.Column('id_atleta', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('posicao', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('peso_atual', sa.Float(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['usuario.id'], name=op.f('fk_atleta_user_usuario')),
    sa.PrimaryKeyConstraint('id_atleta', name=op.f('pk_atleta'))
    )
    op.create_table('plano_treino',
    sa.Column('id_plano', sa.Integer(), nullable=False),
    sa.Column('nome_plano', sa.String(), nullable=True),
    sa.Column('objetivo', sa.String(), nullable=True),
    sa.Column('id_atleta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_atleta'], ['atleta.id_atleta'], name=op.f('fk_plano_treino_id_atleta_atleta')),
    sa.PrimaryKeyConstraint('id_plano', name=op.f('pk_plano_treino'))
    )
    op.create_table('registro_evolucao',
    sa.Column('id_registro', sa.Integer(), nullable=False),
    sa.Column('data_treino', sa.Date(), nullable=True),
    sa.Column('carga_kg', sa.Float(), nullable=True),
    sa.Column('repeticoes', sa.SmallInteger(), nullable=True),
    sa.Column('id_atleta', sa.Integer(), nullable=True),
    sa.Column('id_exercicio', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_atleta'], ['atleta.id_atleta'], name=op.f('fk_registro_evolucao_id_atleta_atleta')),
    sa.ForeignKeyConstraint(['id_exercicio'], ['exercicio.id_exercicio'], name=op.f('fk_registro_evolucao_id_exercicio_exercicio')),
    sa.PrimaryKeyConstraint('id_registro', name=op.f('pk_registro_evolucao'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registro_evolucao')
    op.drop_table('plano_treino')
    op.drop_table('atleta')
    op.drop_table('usuario')
    op.drop_table('exercicio')
    # ### end Alembic commands ###
