"""Criei o banco de dados

Revision ID: f10511572321
Revises: 
Create Date: 2026-05-01 22:00:58.195043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f10511572321'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercicio',
    sa.Column('id_exercicio', sa.Integer(), nullable=False),
    sa.Column('nome_exercicio', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_exercicio')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('sobrenome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('atleta',
    sa.Column('id_atleta', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('posicao', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('peso_atual', sa.Float(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id_atleta')
    )
    op.create_table('plano_treino',
    sa.Column('id_plano', sa.Integer(), nullable=False),
    sa.Column('nome_plano', sa.String(), nullable=True),
    sa.Column('objetivo', sa.String(), nullable=True),
    sa.Column('id_atleta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_atleta'], ['atleta.id_atleta'], ),
    sa.PrimaryKeyConstraint('id_plano')
    )
    op.create_table('registro_evolucao',
    sa.Column('id_registro', sa.Integer(), nullable=False),
    sa.Column('data_treino', sa.Date(), nullable=True),
    sa.Column('carga_kg', sa.Float(), nullable=True),
    sa.Column('repeticoes', sa.SmallInteger(), nullable=True),
    sa.Column('id_atleta', sa.Integer(), nullable=True),
    sa.Column('id_exercicio', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_atleta'], ['atleta.id_atleta'], ),
    sa.ForeignKeyConstraint(['id_exercicio'], ['exercicio.id_exercicio'], ),
    sa.PrimaryKeyConstraint('id_registro')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registro_evolucao')
    op.drop_table('plano_treino')
    op.drop_table('atleta')
    op.drop_table('usuario')
    op.drop_table('exercicio')
    # ### end Alembic commands ###
